name			= "6MD Zeus Modules";					// Name of your mod
author			= "6MD Dev Team";				// Affects Arma 3 Launcher, when the mod are loaded as local
logo			= "\A6MD\Zeus_Modules\core\icons\Logo_6MD.paa";			// Logo displayed in the main menu
logoOver		= "\A6MD\Zeus_Modules\core\icons\Logo_6MD.paa";	// When the mouse is over, in the main menu
tooltip			= "6MD Zeus Modules";
tooltipOwned	= "6MD Zeus Modules";				// Tool tip displayed when the mouse is left over, in the main menu
picture			= "\A6MD\Zeus_Modules\core\icons\Logo_6MD.paa";		// Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName		= "GitHub";
action			= "https://github.com/my-mod-page";			// Website URL, that can be accessed from the expansions menu
overview		= "6th Marron Division Zeus Modules";	// Supports structured text
hideName		= 0;						// Hide the extension name
hidePicture		= 0;						// Hide the extension menu
dlcColor[]		= { 0.23, 0.39, 0.30, 1 };	// Color used for DLC stripes and backgrounds (RGBA)
logoSmall		= "\A6MD\Zeus_Modules\core\icons\Logo_6MD.paa";		// Display in creative lists, next to the entities added by the mod