name = "6th Maroon Division All in one mod"
author = "6MD Dev Team"
prefix = "All_in_One"
mainprefix = "A6MD"

[version]
major = 1 # Overrides path when set
minor = 1
patch = 2
build = 23 # Optional
git_hash = 0 # Default: 8

[hemtt.release]
archive = false